spring:
  application:
    name: FilterRecipe
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 2000000
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: 2592000000 # 1? (30?)
    header: Authorization
  refresh:
    expiration: 2592000000 # 1? (30?)
    header: Authorization-refresh